//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeFinance.UI.AccountNotificatorServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountNotificatorServiceReference.IAccountNotificatorService")]
    public interface IAccountNotificatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountNotificatorService/StartUpdateAccounts", ReplyAction="http://tempuri.org/IAccountNotificatorService/StartUpdateAccountsResponse")]
        void StartUpdateAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountNotificatorService/StartUpdateAccounts", ReplyAction="http://tempuri.org/IAccountNotificatorService/StartUpdateAccountsResponse")]
        System.Threading.Tasks.Task StartUpdateAccountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountNotificatorService/StopUpdateAccounts", ReplyAction="http://tempuri.org/IAccountNotificatorService/StopUpdateAccountsResponse")]
        void StopUpdateAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountNotificatorService/StopUpdateAccounts", ReplyAction="http://tempuri.org/IAccountNotificatorService/StopUpdateAccountsResponse")]
        System.Threading.Tasks.Task StopUpdateAccountsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountNotificatorServiceChannel : HomeFinance.UI.AccountNotificatorServiceReference.IAccountNotificatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountNotificatorServiceClient : System.ServiceModel.ClientBase<HomeFinance.UI.AccountNotificatorServiceReference.IAccountNotificatorService>, HomeFinance.UI.AccountNotificatorServiceReference.IAccountNotificatorService {
        
        public AccountNotificatorServiceClient() {
        }
        
        public AccountNotificatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountNotificatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountNotificatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountNotificatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartUpdateAccounts() {
            base.Channel.StartUpdateAccounts();
        }
        
        public System.Threading.Tasks.Task StartUpdateAccountsAsync() {
            return base.Channel.StartUpdateAccountsAsync();
        }
        
        public void StopUpdateAccounts() {
            base.Channel.StopUpdateAccounts();
        }
        
        public System.Threading.Tasks.Task StopUpdateAccountsAsync() {
            return base.Channel.StopUpdateAccountsAsync();
        }
    }
}
